services:
  db:
    image: postgres:latest
    container_name: sanctions_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sanctions
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  neo4j:
    image: neo4j:latest
    container_name: sanctions_neo4j
    restart: always
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol
    environment:
      NEO4J_AUTH: neo4j/password # Default username/password
    volumes:
      - neo4jdata:/data

  faiss:
    image: daangn/faiss-server:latest
    container_name: sanctions_faiss
    restart: always
    ports:
      - "50051:50051"
    volumes:
      - faissdata:/data


volumes:
  pgdata:
  neo4jdata:
  faissdata:
