global:
  scrape_interval: 15s

scrape_configs:
- job_name: minio-files
  bearer_token: ${MINIO_FILES_BEARER_TOKEN}
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['minio-files:${MINIO_FILES_PORT}']
