name: Run Tests and Measure Coverage

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # --- Development Environment ---
      CLOUD_ENV_OVERRIDE: aws

      # --- PostgreSQL ---
      POSTGRES_DB: sanctions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      # --- pgAdmin ---
      PGADMIN_EMAIL: admin@admin.com
      PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
      PGADMIN_PORT: 5050

      # --- Neo4j ---
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      NEO4J_BOLT_PORT: 7687
      NEO4J_HTTP_PORT: 7474

      # --- Milvus ---
      MILVUS_GRPC_PORT: 19530
      MILVUS_HTTP_PORT: 9091

      # --- ETCD ---
      ETCD_ROOT_USER: root
      ETCD_ROOT_PASSWORD: ${{ secrets.ETCD_ROOT_PASSWORD }}
      ETCD_PORT: 2379

      # --- MinIO ---
      MINIO_PORT: 9000
      MINIO_CONSOLE_PORT: 9001
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}

      # --- MinIO Files ---
      MINIO_FILES_PORT: 9100
      MINIO_FILES_CONSOLE_PORT: 9101
      MINIO_FILES_ROOT_USER: miniofilesadmin
      MINIO_FILES_ROOT_PASSWORD: ${{ secrets.MINIO_FILES_ROOT_PASSWORD }}

      # --- Azurite ---
      AZURITE_BLOB_PORT: 10000
      AZURITE_QUEUE_PORT: 10001
      AZURITE_TABLE_PORT: 10002

      # --- Attu ---
      ATTU_PORT: 8006
      ATTU_HOST: 0.0.0.0
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530

      # --- Common ---
      TZ: UTC

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest --cov --cov-branch --cov-report=xml
      continue-on-error: true

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: edwardlc0000/OpenGraphIntel
